# Generated by Django 5.2 on 2025-05-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_access_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personality_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
