# Generated by Django 5.2 on 2025-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_prizeconfig_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizeconfig',
            name='trigger_phrases',
            field=models.TextField(help_text='List of specific phrases that trigger a win'),
        ),
    ]
