# Generated by Django 5.2 on 2025-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_prizeconfig_trigger_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizeconfig',
            name='max_winners',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of users that can win this prize.'),
        ),
        migrations.AlterField(
            model_name='prizeconfig',
            name='trigger_phrases',
            field=models.TextField(help_text='List of specific phrases that trigger a win, separated by commas.'),
        ),
    ]
