# Generated by Django 5.2 on 2025-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_prizeconfig_max_winners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizeconfig',
            name='max_winners',
        ),
        migrations.RemoveField(
            model_name='prizeconfig',
            name='prize_amount',
        ),
        migrations.AddField(
            model_name='prizeconfig',
            name='prize_description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the prize.', null=True),
        ),
        migrations.AlterField(
            model_name='prizeconfig',
            name='prize_name',
            field=models.CharField(help_text='Title or description of the prize (e.g., 100 $BERA, NFT, Whitelist)', max_length=255),
        ),
    ]
